### PR TITLE
Fix url typo

### PR DESCRIPTION
**Pull request by nicoman**
Fix link to http://gist.github.com/

### CODE REVIEW

**Comment by willingc** [comment]
@econchick +1 Ready to merge.
Thanks @nicoman

**Comment by econchick** [comment]
Hmm @willingc looks like you may be interested in helping manage this repo :-D any interest in being added as a collaborator for help with these PRs? :D

Thanks @nicoman ! Merged, will deploy when I get to my laptop later today.

**Comment by willingc** [comment]
@econchick Well since I was going to work on some of these with PyLadies here. Why not :)

**Comment by nicoman** [comment]
Thank you all :)

**Pull request merged**
